# Site Settings
title: DevSV
description: Blog de nerd
baseurl: ""
url: "http://www.devsv.com.br"
twitter_username: devsvbr

# Handling Reading
include: ['_pages']
exclude: ['browserslist','gulpfile.js','node_modules','package.json','_src']

# Markdown Processor
kramdown:
  input: GFM
