# Site Settings
title: DevSV
description:
  pt: Programação descontraída no estilo caiçara
  en: Caiçara-like playful programming
baseurl: ""
url: "http://www.devsv.com.br"
twitter_username: devsvbr

# Collections
collections:
  toc:
    output: true
    permalink: /:collection/:path

# Handling Reading
include: ['_pages']
exclude: ['browserslist','gulpfile.js','node_modules','package.json','_src']

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      lang: "pt"
  -
    scope:
      path: ""
      type: "pages"
    values:
      type: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      type: "post"

# Markdown Processor
kramdown:
  input: GFM
